# Owner of the GitHub repository
owner: SRESchool

# Name of the GitHub repository
repo: All-DevOpsSchool-Websites-Uptime-Monitor

user-agent: pritesh-1904
skipReadme: true
skipDescription: true
skipTopics: true

# List of websites to monitor for uptime and SSL
sites:
  - name: aiopsschool.com
    url: https://aiopsschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: aiuniverse.xyz
    url: https://aiuniverse.xyz
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: BESTDEVOPS.COM
    url: https://bestdevops.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: cloudopsnow.in
    url: https://cloudopsnow.in
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: xopsschool.com
    url: https://xopsschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: debug.school
    url: https://debug.school
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: DEVOPSCONSULTING.IN
    url: https://devopsconsulting.in
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: devopsfreelancer.com
    url: https://devopsfreelancer.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: devopsschool.com
    url: https://devopsschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: devopsschool.nl
    url: https://devopsschool.nl
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: devopsschool.jp
    url: https://devopsschool.jp
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: devopsschool.org
    url: https://devopsschool.org
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: devopsschool.xyz
    url: https://devopsschool.xyz
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: devopssupport.in
    url: https://devopssupport.in
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: devsecopsnow.com
    url: https://devsecopsnow.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: devsecopsschool.com
    url: https://devsecopsschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: finopsschool.com
    url: https://finopsschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: freeebooks.xyz
    url: https://freeebooks.xyz
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: noopsschool.com
    url: https://noopsschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: quantumopsschool.com
    url: https://quantumopsschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: quantumuting.com
    url: https://quantumuting.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: robotsops.com
    url: https://robotsops.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: sreschool.in
    url: https://sreschool.in
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: theaiops.com
    url: https://theaiops.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: thedataops.org
    url: https://thedataops.org
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: sreschool.com
    url: https://sreschool.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
  - name: SCMGALAXY.COM
    url: https://scmgalaxy.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true  
    port: 80, 443
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: null
  baseUrl: /All-DevOpsSchool-Websites-Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png
  name: DevopsSchool Websites Uptime Monitor
  introTitle: DevopsSchool Websites Status
  introMessage: This page shows the uptime and SSL status of DevopsSchool websites.
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.ico
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Workflow schedule (every 5 minutes)
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
  ssl: "*/5 * * * *"

# Committer configuration
committer:
  name: Pritesh
  email: contact@motoshare.in

# Email notification configuration
notifications:
  - type: email
    smtpTo: contact@motoshare.in
    smtpFrom: contact@motoshare.in
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: contact@motoshare.in
    smtpPassword: kmxg nshc vsrf kxqj

# Assignees for issues
assignees:
  - pritesh-1904
